[[block]]
contains = "Step"
start_new_record = true
columns = [
  { field = "step", index = 1 },
  { field = "time", index = 2 },
  { field = "dt", index = 3 },
  { field = "cfl", index = 4 },
  { field = "solve_time", index = 6 },
]

[[block]]
contains = "PRES gmres"
columns = [
  { field = "gmres_iter", index = 2 },
  { field = "gmres_residual", index = 3 },
]

[[block]]
contains = "AMP"
columns = [
  { field = "cum_gr", index = 4 },
  { field = "step_gr", index = 5 },
  { field = "cum_error", index = 6 }
]
